- name: Windows | Add the dvorak keyboard layout
  win_shell: $langList = Get-WinUserLanguageList; $langList[0].InputMethodTips[0]="{{layout}}"; Set-WinUserLanguageList -LanguageList $langList -Force
